routes/web.php
<?php

use App\Http\Controllers\AdSpacesController;
use App\Http\Controllers\AlbumCategoriesController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\CashPaymentController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmojiController;
use App\Http\Controllers\DBDownloadController;
use App\Http\Controllers\FollowersController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\MailSettingController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\NavigationController;
use App\Http\Controllers\NewsLetterController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\PollController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RssFeedController;
use App\Http\Controllers\seoToolsController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SocialAuthController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//
//Route::get('/', function () {
//    return (! Auth::check()) ? view('auth.login') : Redirect::to(getDashboardURL());
//})->name('login');

// Update profile
Route::middleware('auth', 'xss', 'verified.user')->group(function () {
    Route::get('/profile/edit', [UserController::class, 'editProfile'])->name('profile.setting');
    Route::put('/profile/update', [UserController::class, 'updateProfile'])->name('update.profile.setting');
    Route::put('/change-user-password', [UserController::class, 'changePassword'])->name('user.changePassword');
});

Route::get('/login/{provider}', [SocialAuthController::class, 'redirectToSocial'])->name('social.login');
Route::get('/login/{provider}/callback', [SocialAuthController::class, 'handleSocialCallback']);

Route::prefix('admin')->middleware('auth', 'xss', 'verified.user')->group(function () {
    //admin dashboard route
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/chart', [DashboardController::class, 'getChart'])->name('dashboard.chart');

    Route::get('/generate-sitemap', function () {
        \Illuminate\Support\Facades\Artisan::call('generate:sitemap');
        
        dump("Sitemap generated successfully");

        sleep(2);

        return redirect(route('admin.dashboard'));
    });

    //category
    Route::middleware('permission:manage_categories')->group(function () {
        Route::resource('categories', CategoryController::class);
        Route::post('categories/{category}/update', [CategoryController::class, 'update'])->name('category.update');
        Route::delete('categories/{category}', [CategoryController::class, 'destroy'])->name('category.destroy');
    });
    Route::middleware('permission:cash_payment')->group(function () {
        Route::get('cash-payment', [CashPaymentController::class, 'index'])->name('cash-payment');
        Route::get('subscribed-user-plans',
            [SubscriptionController::class, 'subscribedUserPlans'])->name('subscribed.user.plans');
        Route::get('/subscribedPlan/{id}/edit',
            [SubscriptionController::class, 'userSubscribedPlanEdit'])->name('subscription.user.plan.edit');
        Route::get('/subscribedPlan/{id}/update',
            [SubscriptionController::class, 'userSubscribedPlanUpdate'])->name('subscription.user.plan.update');
       
        //sub category
        Route::get('/download-attachment/{id}', [SubscriptionController::class, 'downloadAttachment']);
    });
    Route::get('/planSubscription/{id}', [SubscriptionController::class, 'planStatus'])->name('subscription.status');
    Route::middleware('permission:manage_sub_categories')->group(function () {
        Route::resource('sub-categories', SubCategoryController::class);
    });

    //Page

    Route::middleware('permission:manage_pages')->group(function () {
        Route::resource('pages', PageController::class);
        Route::post('image-store', [PageController::class, 'imgUpload'])->name('editor.image-upload');
        Route::get('image-get', [PageController::class, 'imageGet'])->name('editor.image-get');
        Route::post('pages-visibility', [PageController::class, 'visibility'])->name('page.visibility');
        Route::get('page-image/{id}', [PageController::class, 'imageDelete'])->name('page-image.destroy');
    });

    //set Language
    Route::get('change-language/{key}', [UserController::class, 'setLanguage'])->name('change-Language');

    //update darkMode Field
    Route::get('update-dark-mode', [UserController::class, 'updateDarkMode'])->name('update-dark-mode');

    Route::get('comment-status/{key}', [CommentController::class, 'commentStatus'])->name('admin.comment-status');
    // Role route
    Route::middleware('permission:manage_roles|manage_roles_permission')->group(function () {
        Route::resource('roles', RoleController::class);
    });

    // Settings routes
    Route::middleware('permission:manage_settings')->group(function () {
        Route::get('/settings', [SettingController::class, 'index'])->name('setting.index');
        Route::post('/settings', [SettingController::class, 'update'])->name('setting.update');
        Route::post('/payment-settings', [SettingController::class, 'paymentUpdate'])->name('payment-setting.update');
    });

    // Contacts routes
    Route::middleware('permission:manage_contacts')->group(function () {
        Route::get('/contacts', [ContactController::class, 'listContact'])->name('contacts.index');
        Route::get('/contacts/show/{id}', [ContactController::class, 'show'])->name('contacts.show');
        Route::delete('/contacts/{id}', [ContactController::class, 'removeContact'])->name('Contacts.destroy');
    });

    //Mail
    Route::middleware('permission:manage_mail_setting')->group(function () {
        Route::resource('/mails', MailSettingController::class);
        Route::post('/mails-verification', [MailSettingController::class, 'mail'])->name('mails-verification');
        Route::post('/mails-contact', [MailSettingController::class, 'contactMessage'])->name('mails.contact');
        Route::post('/mails-send-test', [MailSettingController::class, 'sendTestemail'])->name('mails-send-test');
    });
    // Staff route
    Route::middleware('permission:manage_staff')->group(function () {
        Route::resource('staff', StaffController::class);
        Route::get('resend-email/{id}', [StaffController::class, 'resendEmail'])->name('resend-email');
    });

    // album category route
    Route::middleware('permission:manage_albums_category')->group(function () {
        Route::resource('album-categories', AlbumCategoriesController::class);
    });
    //Plans
    Route::middleware('permission:manage_plans')->group(function () {
        Route::resource('plans',PlanController::class);
        Route::put('plans/{plan}/is_default',[PlanController::class, 'planMakeDefault'])->name('plan.make-default');
    });
    //Add-Post Route
    Route::middleware('permission:manage_all_post')->group(function () {
        Route::resource('posts', PostController::class);
        Route::post('posts/language', [PostController::class, 'language'])->name('posts.language');
        Route::post('posts/category', [PostController::class, 'category'])->name('posts.category');
        Route::post('posts-subcategory', [PostController::class, 'categoryFilter'])->name('posts.categoryFilter');
        Route::post('posts/image-store', [PostController::class, 'imgUpload'])->name('editor.post-image-upload');
        Route::get('post-upload-image-get', [PostController::class, 'imageGet'])->name('post-upload-image-get');
        Route::get('post/image/{id}', [PostController::class, 'imageDelete'])->name('post-image.destroy');
        Route::get('post-format', [PostController::class, 'postFormat'])->name('post_format');
        Route::get('post-type', [PostController::class, 'postType'])->name('post_type');
        Route::post('open-ai',[PostController::class, 'openAi'])->name('open_ai');
        Route::post('get-video', [PostController::class, 'getVideoByUrl'])->name('get-video-by-url');
        Route::get('bulk-post', [PostController::class, 'bulkPost'])->name('bulk-post-index');
        Route::get('bulk-post-ids-list', [PostController::class, 'idsList'])->name('bulk-post-ids-list');
        Route::get('bulk-post-documentation', [PostController::class, 'Documentation'])->name('bulk-post-documentation');
        Route::get('export', [PostController::class, 'export'])->name('export-csv');
        Route::post('bulk-post-store', [PostController::class, 'bulkPostStore'])->name('bulk-post-store');
       
    });
    Route::middleware('permission:manage_rss_feeds')->group(function () {
        Route::resource('rss-feed', RssFeedController::class);
        Route::post('rss-feed/manuallyUpdate/{rssFeed}', [RssFeedController::class, 'manuallyUpdate'])->name('rss-feed.manuallyUpdate');
    });

    Route::middleware('permission:manage_albums')->group(function () {
        Route::resource('albums', AlbumController::class);
    });

    Route::middleware('permission:manage_language')->group(function () {

resources/views/livewire-tables/rows/album_table.blade.php
<x-livewire-tables::bs5.table.cell>
    {!! $row->name !!}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    @php
        $images = [];
        foreach($row->gallery as $imaga){
            $images[] =  count($imaga->gallery_image);

        }
    @endphp
    {{array_sum($images)}}

</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {!! $row->language->name !!}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell :customAttributes="['class' => 'custom-width-album']">

    <div class="d-flex justify-content-start">
        <a href="javascript:void(0)" data-bs-toggle="tooltip"
           data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{ __('messages.common.edit') }}"
           class="btn px-1 text-primary fs-3 edit-album-btn"  data-id="{{$row['id']}}">
            <i class="fa-solid fa-pen-to-square"></i>
        </a>
        <a href="javascript:void(0)" data-id="{{ $row['id'] }}" data-bs-toggle="tooltip"
           data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{ __('messages.delete') }}"
           class="btn px-1 text-danger fs-3 delete-album-btn">
            <i class="fa-solid fa-trash"></i>
        </a>
    </div>



</x-livewire-tables::bs5.table.cell>

resources/views/livewire-tables/rows/cash_payment_table.blade.php
<style>
    .plan-amount div {
        justify-content: end;
    }

    .date-align div {
        justify-content: center;
    }
</style>
<x-livewire-tables::bs5.table.cell>
    {{ !empty($row->user) ? $row->user->full_name : '' }}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    {{ ($row->plan->name) }}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell class="text-end">
    {{currencyFormat($row->plan_amount,$row->plan->currency->currency_icon) ?? 0}}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell class="text-end">
    {{currencyFormat($row->payable_amount,$row->plan->currency->currency_icon) ?? 0}}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell class="text-center">
    {{ \Carbon\Carbon::parse($row->starts_at)->isoFormat('Do MMMM YYYY')}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell class="text-center">
    {{ \Carbon\Carbon::parse($row->ends_at)->isoFormat('Do MMM YYYY')}}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>

    @if($row->attachment)
        <a href="{{ url('admin/download-attachment'.'/' .$row->id) }}" target="_blank" class="text-decoration-none">Download</a>
    @else
        N/A
    @endif
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    {{$row->notes ?? "N/A"}}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell class="text-center">
    
    @if ($row->payment_type == App\Models\Subscription::MANUALLY)
    <div class="dropdown">
        <a class="btn btn-warning dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
           data-bs-toggle="dropdown" aria-expanded="false">
            {{ __('messages.common.pending') }}
        </a>
        <ul class="dropdown-menu withdraw-approval-dropdown" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href="#" data-id="{{ $row->id }}" id="approvedPayment">{{ __('messages.common.approved') }}</a>
            </li>
            <li><a class="dropdown-item" href="#" data-id="{{ $row->id }}"
                   id="rejectedPayment">{{ __('messages.common.rejected') }}</a>
            </li>
        </ul>
    </div>
    @elseif($row->payment_type == App\Models\Subscription::REJECTED)
        <a class="text-danger bg-light-danger badge text-decoration-none"> Rejected</a>

    @else
        <span class="badge bg-light-success">Received</span>
    @endif

</x-livewire-tables::bs5.table.cell>

resources/views/livewire-tables/rows/news_letter_table.blade.php
<x-livewire-tables::bs5.table.cell>
    {{ $row->email }}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell class="text-center">
    <div class="d-flex justify-content-center">
        <a href="javascript:void(0)" data-id="{{$row['id']}}" data-bs-toggle="tooltip"
           data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{ __('messages.delete') }}"
           class="btn px-1 text-danger fs-3 delete-subscriber-btn">
            <i class="fa-solid fa-trash"></i>
        </a>
    </div>
</x-livewire-tables::bs5.table.cell>

resources/views/livewire-tables/rows/post_table.blade.php
<x-livewire-tables::bs5.table.cell :customAttributes="['class' => 'd-flex']">

    @php
        $image = $row->post_types == \App\Models\Post::VIDEO_TYPE_ACTIVE ? (!empty($row->postVideo->thumbnail_image_url) ? $row->postVideo->thumbnail_image_url : $row->postVideo->uploaded_thumb ?? '') : $row->post_image;
    @endphp
    <div class="d-flex align-items-center">
        <div class=" position-relative overflow-hidden width-custom">
            <a href="{{ $image }}" data-lightbox="image-{{$row->id}}">
                <img src="{{ $image }}" class="float-start  width-custom">
                @if($row->status == 0)
                    <span class="badge badge-tag bg-warning position-absolute">{{__('messages.post.draft_post')}}</span>
                @endif
            </a>
        </div>
        <div class="d-flex flex-column align-items-start">
            <a href="{{ route('detailPage',$row->slug) }}"
               class="mb-0 ps-2 lh-15 text-decoration-none {{ $row->status != 0 ? '' : 'pe-none' }} {{ $row->visibility != 0 ? '' : 'pe-none' }}"
               target="_blank"> {!!  $row->title !!} </a>
            <div>
            <span class="badge bg-light-primary   fs-7 m-1 ">
                {!!$row->type_name  !!}
             </span>
            <span class="badge bg-light-{{getRandomColor($loop->index)}}  fs-7 m-1 ">
                {!! $row->category->name !!}
             </span>
                <span class="badge bg-light-primary  fs-7 m-1 ">
                    <i class="fa-solid fa-language"></i>
                {!! $row->language->name !!}
             </span>
                <span class="badge bg-light-{{getRandomColor($loop->index)}}  fs-7 m-1 ">
                     <i class="fa-solid fa-eye fs-12 text-gray me-1"></i>
                    {{getPostViewCount($row->id)}}
             </span>
            </div>
        </div>
    </div>
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell :customAttributes="['style' => 'width:100px']">
    <label class="form-check form-switch form-check-custom form-check-solid form-switch-sm d-flex justify-content-start cursor-pointer">
        <input type="checkbox" name="status" class="form-check-input  cursor-pointer" value="{{$row->show_on_headline}}" wire:click="updateHeadline({{$row['id']}})"
                {{ (($row->show_on_headline)=="1") ? 'checked' : ''}}>
        <span class="custom-switch-indicator"></span>
    </label>
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    <label class="form-check form-switch form-check-custom form-check-solid form-switch-sm d-flex justify-content-start cursor-pointer">
            <input type="checkbox" name="status" class="form-check-input post-visibility cursor-pointer" value="{{$row->visibility}}" wire:click="updateVisibility({{$row['id']}})"
                {{ (($row->visibility)=="1") ? 'checked' : ''}}>
        <span class="custom-switch-indicator"></span>
    </label>
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    <label class="form-check form-switch form-check-custom form-check-solid form-switch-sm d-flex justify-content-start cursor-pointer">
        <input type="checkbox" name="status" class="form-check-input  cursor-pointer" value="{{$row->featured}}" wire:click="updateFeatured({{$row['id']}})"
                {{ (($row->featured)=="1") ? 'checked' : ''}}>
        <span class="custom-switch-indicator"></span>
    </label>
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    {{ \Carbon\Carbon::parse($row->created_at)->isoFormat('Do MMM, YYYY')}}
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    <div class="action-btn d-flex option align-items-center">
        <div class="dropdown">
            <button class="btn btn-light btn-sm dropdown-toggle hide-arrow" type="button" id="dropdownMenuButton1"
                    data-bs-toggle="dropdown" aria-expanded="false">
                {{__('messages.common.select_an_option')}}
            </button>
            <ul class="dropdown-menu min-width-220" aria-labelledby="dropdownMenuButton1">
                <li>
                    @if(Auth::user()->hasRole('customer'))
                        <a href="{{route('customer-posts.edit', $row['id'])}}"
                           class="dropdown-item posts-edit-btn px-3 py-1 text-decoration-none">
                            {{__('messages.common.edit')}}
                        </a>
                    @endif
                    @if(!Auth::user()->hasRole('customer'))
                        <a href="{{route('posts.edit', $row['id'])}}"
                           class="dropdown-item posts-edit-btn px-3 py-1 text-decoration-none">
                            {{__('messages.common.edit')}}
                        </a>
                    @endif
                </li>
                <li>
                    @if(!Auth::user()->hasRole('customer'))
                        <a href="{{route('posts.show',$row['id'])}}"
                           class="dropdown-item px-3 py-1 text-decoration-none">
                            {{__('messages.common.view')}}
                        </a>
                    @endif
                    @if(Auth::user()->hasRole('customer'))
                        <a href="{{route('customer-posts.show',$row['id'])}}"
                           class="dropdown-item px-3 py-1 text-decoration-none">
                            {{__('messages.common.view')}}
                        </a>
                    @endif
                </li>

                @if(!$row->status)
                <li>
                    <a href="#" class="dropdown-item px-3 py-1 text-decoration-none"
                       wire:click="publishPost({{$row['id']}})">
                            {{__('messages.post.publish_post')}}
                    </a>
                </li>
                @endif
                <li>
                    <a href="#" class="dropdown-item px-3 py-1 text-decoration-none"
                       wire:click="updateBreaking({{$row['id']}})">
                        @if($row->breaking)
                            {{__('messages.post.remove_to_breaking')}}
                        @else
                            {{__('messages.post.add_to_breaking')}}
                        @endif
                    </a>
                </li>
                <li>
                    <a href="#" class="dropdown-item px-3 py-1 text-decoration-none"
                       wire:click="updateSlider({{$row['id']}})">
                        @if($row->slider)
                            {{__('messages.post.remove_to_slider')}}
                        @else
                            {{__('messages.post.add_to_slider')}}
                        @endif
                    </a>
                </li>
                <li>
                    <a href="#" class="dropdown-item px-3 py-1 text-decoration-none"
                       wire:click="updateRecommended({{$row['id']}})">
                        @if($row->recommended)
                            {{__('messages.post.remove_to_recommended')}}
                        @else
                            {{__('messages.post.add_to_recommended')}}
                        @endif
                    </a>
                </li>
            </ul>
        </div>
        <a href="javascript:void(0)" data-id="{{$row['id']}}" data-bs-toggle="tooltip"
           data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{ __('messages.delete') }}"
           class="btn px-2 text-danger fs-3 delete-posts-btn">
            <i class="fa-solid fa-trash"></i>
        </a>
    </div>

</x-livewire-tables::bs5.table.cell>

resources/views/livewire-tables/rows/rss_feed_table.blade.php
<x-livewire-tables::bs5.table.cell>
    {{ $row->feed_name}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    <a href="{{ $row->feed_url}}" target="_blank">{{ $row->feed_url}}</a>
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {{ count($row->posts) .'/' .$row->no_post}}
</x-livewire-tables::bs5.table.cell>
{{--<x-livewire-tables::bs5.table.cell>--}}
{{--    {{ $row->no_post}}--}}
{{--</x-livewire-tables::bs5.table.cell>--}}
<x-livewire-tables::bs5.table.cell>
    {{ $row->language->name}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {{ $row->category->name}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {{ $row->user->full_name}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
        <span class="badge {{App\Models\RssFeed::YES == $row->auto_update ?  'bg-success' : 'bg-danger'}}  fs-7 m-1">
        {{App\Models\RssFeed::AUTO_UPDATE[$row->auto_update]}}
    </span>
    <div>
        <a href="javascript:void(0)" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="
{{__('messages.sync')}}"
           class="btn btn-primary px-2 py-1  rss-feed-manually-update" data-id="{{$row->id}}">
            <i class="fa-solid fa-repeat"></i> {{__('messages.sync')}}
        </a>
    </div>
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    <a href="{{ route('rss-feed.edit', $row->id) }}" data-bs-toggle="tooltip"
       data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{ __('messages.common.edit') }}"
       class="btn px-1 text-primary fs-3 role-edit-btn"  data-id="{{$row->id}}">
        <i class="fa-solid fa-pen-to-square"></i>
    </a>
    <a href="javascript:void(0)" data-id="{{ $row->id }}" data-bs-toggle="tooltip"
       data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{ __('messages.delete') }}"
       class="btn px-1 text-danger fs-3 rss-feed-delete-btn">
        <i class="fa-solid fa-trash"></i>
    </a>
</x-livewire-tables::bs5.table.cell>

resources/views/livewire-tables/rows/staff_table.blade.php
<x-livewire-tables::bs5.table.cell>
    <div class="d-flex align-items-center">
        <div class="me-5">
            <img src="{{ $row->profile_image }}" alt="" width="50" height="50" class="rounded-circle object-cover">
        </div>
        <div class="d-flex justify-content-start flex-column">
            <span class="text-muted fw-bold text-muted d-block fs-7">{!! $row->first_name !!} {!! $row->last_name !!}</span>
            <span class="text-muted text-muted d-block fs-7">{{ $row->email }} </span>
        </div>
    </div>
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {!! !empty($row->subscription) ? $row->subscription->plan->name : 'N/A' !!}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {!!  $row->username ?? 'N/A' !!}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {!! !empty($row->roles[0]) ? $row->roles[0]->display_name : 'N/A' !!}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>

    <label class="form-check form-switch form-check-custom form-check-solid form-switch-sm d-flex justify-content-start cursor-pointer">
        <input type="checkbox" name="status" class="form-check-input user-active cursor-pointer"
               wire:change="emailVerified({{$row->id}})"
               value="{{$row->email_verified_at}}" {{ (($row->email_verified_at)!=null) ? 'checked' : ''}} {{(($row->email_verified_at) != null) ? 'disabled' : ''}}>

        <span class="custom-switch-indicator"></span>
    </label>
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell>
    <label class="form-check form-switch form-check-custom form-check-solid form-switch-sm d-flex justify-content-start cursor-pointer">
        <input type="checkbox" name="status" class="form-check-input user-active cursor-pointer"
               wire:change="updateStatus({{$row->status}},{{$row->id}})" value="{{$row->status}}"
                {{ (($row->status)=="1") ? 'checked' : ''}}>
        <span class="custom-switch-indicator"></span>
    </label>
</x-livewire-tables::bs5.table.cell>

<x-livewire-tables::bs5.table.cell :customAttributes="['class' => 'custom-width-album']">
    <div class="d-flex justify-content-start">
        @if(($row->email_verified_at) == null)
            <a href="javascript:void(0)" data-bs-toggle="tooltip"
               data-bs-placement="top" data-bs-trigger="hover"
               data-bs-original-title="{{__('messages.common.send_email')}}"
               class="btn px-0 text-primary px-2 fs-3 resend-email-staff-btn" data-id="{{$row->id}}">
                <i class="fa-solid fa-envelope"></i>
            </a>
        @endif
        <a href="{{route('staff.edit',$row['id'])}}" data-bs-toggle="tooltip"
           data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{__('messages.common.edit')}}"
           class="btn px-0 text-primary fs-3  staff-edit-btn" data-id="{{$row->id}}">
            <i class="fa-solid fa-pen-to-square"></i>
        </a>
        <a href="javascript:void(0)" data-id="{{$row['id']}}" data-bs-toggle="tooltip"
           data-bs-placement="top" data-bs-trigger="hover" data-bs-original-title="{{ __('messages.delete') }}"
           class="btn px-2 text-danger fs-3 delete-staff-btn">
            <i class="fa-solid fa-trash"></i>
        </a>
    </div>
</x-livewire-tables::bs5.table.cell>